language: node_js
node_js: node
deploy:
  provider: heroku
  edge: true
  api_key:
    secure: nJQb/ZUYNIHKuErWH7sIrsa1ubc5j2+17F/2GMPhxSEuAOHvxNPj9up0Ss8ZTvObDXRakHn/IZUgD4v1iWj9lWsljo1W/51DT2bJeoZRHHzrKKF9cO7jLCw2x+7Yer1ufy0aq8Ldl4XOAJXqpHg39DyaPqCVb2b6gZrp+1E1UCzWs0m2y/+/F1Z2rOak2b5gGIp1x9gynUK56qjvjiERI+XHUOPat6+UEF7e3DHZxptZyB9sheBg+WaMLE8AUCEXM/a1q/yrKzH1GqUaLDYOSEvV9fvGqoGCv4YdciNRqurT9NOe1iXbSQgVXPEZ/zVJdOs2kDLDJB2mq65ILsKMPCga1wM9G5pCcVLg/ODGnzulBG25RqIaOTaKbcAJ6ZviKQTSaBJj+XM46EIQwZYdA52jSCMUk2ndgnkC5AauGhPfQd/nxSI8hMNYDvD8jN30j4ZSUX4KExzvoRjR9IXRcVE2iAjP8HnEZAQKvPlPe12N5Gi7AYNZRnHjX3BgkI2tDBxHm9nQgv1+Nto4WXzxDgBOiZarbVvp+QLuPPT5hMgKqbL2O3/22kkZ3VwEyDXmd9d/IVLybyMWQ88f4raqUmRcHg+KcUeXCFdV5u8V9oWDv5+tC5IVt+y1P2B3V22LHbDhrcCJ9Ey4VXDMErGpulBsaVTTweMkAUObZsKhpYM=
  app: protected-fjord-96082
  on:
    repo: tranlam10/HappyLyfe
